/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/header/Header.vue')['default']
    HeaderComponents: typeof import('./src/components/header/HeaderComponents.vue')['default']
    HeaderNav: typeof import('./src/components/header/HeaderNav.vue')['default']
    LoginDialog: typeof import('./src/components/login/LoginDialog.vue')['default']
    MySeries: typeof import('./src/components/user/MySeries.vue')['default']
    MySeriesComponent: typeof import('./src/components/series/MySeriesComponent.vue')['default']
    PlayerComponent: typeof import('./src/components/player/player_left/PlayerComponent.vue')['default']
    PlayerInfo: typeof import('./src/components/player/player_left/PlayerInfo.vue')['default']
    PlayerTitle: typeof import('./src/components/player/player_left/PlayerTitle.vue')['default']
    RightContainer: typeof import('./src/components/player/player_right/RightContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeriesAddComponent: typeof import('./src/components/series/SeriesAddComponent.vue')['default']
    SeriesItem: typeof import('./src/components/series/SeriesItem.vue')['default']
  }
}
